### ISSUE TITLE
When widget is disabled remove image button is still being visible and still working

### ISSUE THREAD

**Issue by miratcan** [inventare/django-image-uploader-widget#174]

**Comment by EduardoJM** [comment]
Hello!

Currently, both the widgets and inlines should not work for readonly modes because when set readonly_fields or remove change permissions for admin, the widget is not used to render the page, resulting on a image link.

Is possible to add a property to the widget to disable the edition of it based on some things and remove the edit behaviour of the widget. I will put this on my tasks for this week.

**Comment by EduardoJM** [comment]
This was considered, for now, out of scope of this project. The disabled state (read_only field or admin page without change permission) is not managed by widget, but by the application.
